name: Build Project
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Update and install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build libaio-dev libbluetooth-dev libcapstone-dev libbrlapi-dev libbz2-dev libcap-ng-dev libcurl4-gnutls-dev libgtk-3-dev libibverbs-dev libjpeg8-dev libncurses5-dev libnuma-dev librbd-dev librdmacm-dev libsasl2-dev libsdl2-dev libseccomp-dev libsnappy-dev libssh-dev libvde-dev libvdeplug-dev libvte-2.91-dev libxen-dev liblzo2-dev valgrind xfslibs-dev libnfs-dev libiscsi-dev binwalk p7zip-full qemu-utils adb libusb-1.0-0-dev build-essential libepoxy-dev libdrm-dev libgbm-dev libx11-dev libvirglrenderer-dev libpulse-dev libsdl2-dev libgtk-3-dev
      - uses: actions/checkout@v3
      - name: Check shell scripts
        run: |
          shellcheck -o all build.sh
          git update-index --chmod=+x build.sh
          git update-index --chmod=+x tests/tcg/configure.sh
          git update-index --chmod=+x scripts/git-submodule.sh
      - name: Run build script
        run: |
          mkdir build
          git config --global --add safe.directory /__w/qemu-sideswipe/build
          cd build
          sudo chmod +x ../build.sh
          ../build.sh
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: qemu-sideswipe
          path: qemu-sideswipe.zip
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-hidapi
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_net
            mingw-w64-x86_64-qt6
            mingw-w64-x86_64-python3-pip
            mingw-w64-x86_64-python3-pyopenssl
            mingw-w64-x86_64-nasm
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-mesa
            mingw-w64-x86_64-libepoxy
            git
            zip
      - name: Run build script
        run: |
          mkdir build-msys
          cd build-msys
          msys2 -c '../build-msys.sh'
      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: qemu-sideswipe-w64
          path: qemu-sideswipe-w64.zip
